### ISSUE TITLE
How to support multiple list formats

### ISSUE THREAD

**Issue by santi-g-s** [rajdeep/proton#108]
I want to let the user create both ordered and unordered lists but I'm not sure how to support this.

I tried adding a `@Binding` to the EditorListFormattingProvider but for obvious reasons this affects all lists in the EditorView:

```
class ListFormattingProvider: EditorListFormattingProvider {

    @Binding var listStyle: ListStyle

    init(listStyle: Binding<ListStyle>) {
        _listStyle = listStyle
    }

    let listLineFormatting: LineFormatting = LineFormatting(indentation: 25, spacingBefore: 0)

    func listLineMarkerFor(editor: EditorView, index: Int, level: Int, previousLevel: Int, attributeValue: Any?) -> ListLineMarker {

        switch listStyle {
        case .bullet:
            return BulletSequenceProvider().value(at: index)
        case .numbered:
            if level == 1 {
                return NumberSequenceProvider().value(at: index)
            } else {
                return DashSequenceProvider().value(at: index)
            }
        }


    }
}
```

Is there a way to do this?
Thank you

**Comment by rajdeep** [comment]
The idea of `attributeValue` in `lineMarkerFor()` is so that it can be used to pass the data that one might need to deduce the list type. For eg. you can create a structure/data type that contains the list type besides any other data that you might be keeping in the `attributeValue`. In this function, you can then inspect the value passed in (e.g. `listStyle`) and return the appropriate marker. Hope this helps.
