### ISSUE TITLE
how to change panel state and save it

### ISSUE THREAD

**Issue by hoangnam714** [rajdeep/proton#132]
<img width="262" alt="Screenshot 2021-11-06 at 10 01 17" src="https://user-images.githubusercontent.com/51524705/140756141-3d27d4e9-f836-4435-af9e-e1a0c4a7d71f.png">
how get and set the state of the panel so that when I reload it I can tell it is being selected and deselected

**Comment by rajdeep** [comment]
@hoangnam714, since the `panel` is just a `UIView`, you can add logic to the `panel` itself to fetch its state when it is loaded. You may also add the logic to save the state to your persistent store when the checked state is changed in the view. Doing so, you will be able to keep all your saving/retrieving logic within the view itself. Alternatively, to save state, you may also read the `attributedText` from the `EditorView` and loop over the `attachments` to get to the view that you are interested in, and then read its state. However, the prior approach of keeping logic within the view itself is what I would recommend.

**Comment by hoangnam714** [comment]
Thank you for @rajdeep reply, do you have contact by telegram or other social network, it would be great if some of my questions are answered quickly

**Comment by rajdeep** [comment]
Github is good for any discussion you might want to have. You may also use the [Slack channel](https://join.slack.com/t/proton-etd3355/shared_invite/zt-yyt7um1c-LwQpQWr_OmmZ11_F2sHjTQ).
