### ISSUE TITLE
I'm wanting to automatically replace all people names in a document with buttons. Is there a recommended approach?

### ISSUE THREAD

**Issue by bryan1anderson** [rajdeep/proton#149]
I have an app where a user can type names that need to be automatically matched to their contacts or discovered through use of natural language processing.

    func highlightNames() {
        let attributedText = NSMutableAttributedString(attributedString: editorView.attributedText)
        let names = getNames()
        
        for name in names {
             let ranges = attributedText.string.ranges(of: name)
            for range in ranges {
                attributedText.setAttributes([.foregroundColor: UIColor(.blue), .font: UIFont.systemFont(ofSize: 20, weight: .semibold)], range: range.nsRange(in: attributedText.string))
            }

        }
        editorView.attributedText = attributedText
    }

This is what I'm doing to get names highlighted. But this has inherent issues, for example as I'm typing once it encounters a name it keeps the font attributes as I continue typing.

And I need to make the names tappable.

For example, in iMessage if you type a name it appears grayed out, and then you can tap a name.

I'm trying to figure out if you recommend using attributes or if the better option would be replacing a word with a panel?

**Comment by rajdeep** [comment]
hi @bryan1anderson,
there are a couple of ways you can do this:

1. Create an `InlineAttachment` with the style that you desire and add to the given range. Since this will contain a view, you can style it however you wish and it will not bleed the formatting info to the following text.
2. If you have simple formatting like shown in example above, you can add an additional attribute [lockedAttributes](https://rajdeep.github.io/proton/Extensions/NSAttributedString/Key.html#/s:So21NSAttributedStringKeya6ProtonE16lockedAttributesABvpZ). Any attribute added in the `lockedAttributes` will not be carried forward as content is typed.

For the example above, you can use:
```swift
 let attributes: [NSAttributedString.Key: Any] = [
            NSAttributedString.Key.foregroundColor: UIColor.blue,
            .font: UIFont.systemFont(ofSize: 20, weight: .semibold),
            .lockedAttributes: [NSAttributedString.Key.foregroundColor, .font]
        ]
// add to the desired range
```  
With the `.lockedAttributes`, this is the result:

https://user-images.githubusercontent.com/266423/176988029-cd4a96dd-35d9-411b-8c90-7df33a3cd2f2.mp4
